# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supported', models.BooleanField(default=False)),
                ('network_id', models.IntegerField(default='1')),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortcuts', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project_info',
            fields=[
                ('prj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prj_id', serialize=False, to='param_table_for_customer.Project')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Server_connection_info',
            fields=[
                ('srv_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='param_table_for_customer.Server')),
                ('host', models.CharField(max_length=200)),
                ('host2', models.CharField(max_length=200, null=True)),
                ('port', models.PositiveSmallIntegerField(null=True)),
                ('vpn', models.GenericIPAddressField(null=True, protocol='IPv4')),
                ('dns', models.CharField(max_length=200, null=True)),
                ('url', models.URLField()),
                ('url2', models.URLField(null=True)),
                ('send_to_address', models.GenericIPAddressField(protocol='IPv4')),
                ('send_to_port', models.PositiveSmallIntegerField()),
                ('login', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('stream_path', models.FilePathField(allow_files=False, allow_folders=True, null=True)),
                ('report_path', models.FilePathField(allow_files=False, allow_folders=True, null=True)),
                ('db_login', models.CharField(max_length=200)),
                ('db_password', models.CharField(max_length=200)),
                ('db_port', models.PositiveSmallIntegerField(null=True)),
                ('db_name', models.CharField(max_length=200)),
                ('db_host', models.GenericIPAddressField(protocol='IPv4')),
                ('encryptPK', models.CharField(max_length=200, null=True)),
                ('encryptLK', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='param_table_for_customer.Server'),
        ),
    ]
