# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('param_table_for_customer', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server_connection_info',
            old_name='srv_id',
            new_name='srv',
        ),
        migrations.AlterField(
            model_name='project',
            name='server',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='param_table_for_customer.Server'),
        ),
    ]
