# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('param_table_for_customer', '0005_auto_20171017_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_info',
            name='prj',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='prj_id', serialize=False, to='param_table_for_customer.Project'),
        ),
    ]
