# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param_table_for_customer', '0006_auto_20171017_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_connection_info',
            name='port',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
