# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('param_table_for_customer', '0007_auto_20171017_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='server_connection_info',
            name='srv',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='param_table_for_customer.Server'),
        ),
    ]
