# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param_table_for_customer', '0009_auto_20171017_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_connection_info',
            name='port',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server_connection_info',
            name='send_to_port',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
