# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('param_table_for_customer', '0010_auto_20171017_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server_connection_info',
            name='db_host',
            field=models.GenericIPAddressField(null=True, protocol='IPv4'),
        ),
        migrations.AlterField(
            model_name='server_connection_info',
            name='db_login',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server_connection_info',
            name='db_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server_connection_info',
            name='db_password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='server_connection_info',
            name='port',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='server_connection_info',
            name='send_to_port',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
